### ISSUE TITLE
-1 DB

### ISSUE THREAD

**Issue by ynrrizki** [Zilfs/students-management#2]

**Comment by Zilfs** [comment]
😂😂 wkwkwk ntar gw coba bikin migration nya

**Comment by Zilfs** [comment]
dah update tuh bang.. wkwkwk, tutornya ada di readme

**Comment by ynrrizki** [comment]
gileeeee, jarang-jarang cuk user ci4 bikin migration😱

**Comment by Zilfs** [comment]
wkekekeke
